version: "3"

services:
  flowise:
    image: flowiseai/flowise
    restart: always
    env_file: ".flowise.env"
    ports:
      - "3000:3000"
    volumes:
      - ~/.flowise:/root/.flowise

  chromadb:
    image: chromadb/chroma:0.5.3
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    volumes:
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
      # Read more about deployments: https://docs.trychroma.com/deployment
      - ~/.chroma-data:/chroma/chroma
    env_file: ".chromadb.env"
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    ports:
      - "8000:8000"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
